config/routes.rb
Rails.application.routes.draw do
  post 'page/create', to: 'site#create'

  get 'page/:id' => 'site#show', as: :page

  root 'site#index'

end

app/models/page.rb
class Page < ActiveRecord::Base
  validates :name, :facebook_page_id, :facebook_page_image_url, :facebook_page_url, presence: true
  validates :facebook_page_id, uniqueness: true

  def set_fb_page_data facebook_id
    auth = Koala::Facebook::OAuth.new ENV['FB_APP_ID'], ENV['FB_SECRET']
    token = auth.get_app_access_token
    graph = Koala::Facebook::API.new token

    begin
      page = graph.get_object facebook_id
      image = graph.get_picture facebook_id

      self.name = page['name']
      self.facebook_page_id = page['id']
      self.facebook_page_url = page['link']
      self.facebook_page_image_url = image
    rescue Exception => ex
      puts ex.message
    end
  end

  def get_feed
    auth = Koala::Facebook::OAuth.new ENV['FB_APP_ID'], ENV['FB_SECRET']
    token = auth.get_app_access_token
    graph = Koala::Facebook::API.new token

    graph.get_connections(self.facebook_page_id, 'feed?limit=10')
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/site_controller.rb
class SiteController < ApplicationController
  before_action :set_page, only: [:show]

  def index
    @pages = Page.all
    @page = Page.new
  end

  def create
    @page = Page.new page_params

    @page.set_fb_page_data params[:page][:facebook_page_id]

    respond_to do |format|
      if @page.save
        format.html { redirect_to root_path, notice: 'Facebook Page found and saved yay!' }
      else
        format.html { redirect_to root_path, alert: 'Ooops! Page already saved or not found! :(' }
      end
    end
  end

  def show
    @feed = @page.get_feed()
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_page
      @page = Page.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def page_params
      params.require(:page).permit(:facebook_page_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/site_helper.rb
module SiteHelper
end

app/views/layouts/application.html.haml
!!! 5
%html{ :lang => "en"}
  %head
    %meta{ :charset => "utf-8" }

    %meta{ :name => "viewport", :content => "width=device-width, initial-scale=1.0" }

    %title= content_for?(:title) ? yield(:title) : "Untitled"

    = stylesheet_link_tag "application"
    = javascript_include_tag "vendor/modernizr"
    = csrf_meta_tag

  %body

    .row{ style: 'padding-top: 50px;' }
      .large-12.columns.large-centered
        - if notice
          %p.alert-box.success.round= notice

        - elsif alert
          %p.alert-box.alert.round= alert

    = yield

    = javascript_include_tag "application"

app/views/site/_form.html.haml
= form_for @page, url: page_create_path do |f|
  .row
    .large-12.columns
      = f.text_field :facebook_page_id, placeholder: '(example: 343449308540985)'

  .row
    .large-8.large-centered.columns
      = f.submit 'Add', class: 'button [radius round] expand'

app/views/site/index.html.haml
- content_for :title do
  = "Page Fetcher"

.row
  .large-12.columns.text-center
    %h1 Page Fetcher

.row
  .large-12.columns
    = render 'form'

/ Render the feed here
.row
  .large-12.columns{ role: 'content' }
    - if @pages.size > 0
      - @pages.each do |page|
        .row
          .large-2.columns
            = link_to image_tag(page.facebook_page_image_url), page_path(page)

          .large-10.columns
            %h3
              = link_to page.name, page_path(page)
    - else
      %h2
        No pages have been saved yet!

%br

app/views/site/show.html.haml
- content_for :title do
  = "#{@page.name}'s feed"

.row
  .large-9.columns.large-centered
    .row
      .large-1.columns
        = image_tag @page.facebook_page_image_url
      .large-11.columns
        %h3
          = @page.name

.row{ style: 'padding-top: 50px;' }
  .large-9.columns.large-centered
    - @feed.each_with_index do |item, index|
      .row
        .large-12.columns
          %b
            = item['from']['name']
      .row
        - if item['picture']
          .large-2.columns.small-3
            = image_tag item['picture'], size: '80'
          .large-10.columns
            %p.text-justify
              = item['message']
        - else
          .large-12.columns
            %p.text-justify
              = item['message']
      .row
        .large-12.columns
          %p
            = "#{ time_ago_in_words item['created_time'] } ago"

%br